name: sosreport
version: "3.3-1"
summary: Set of tools to gather troubleshooting data from a system.
description: Sos is a set of tools that gathers information about system
 hardware and configuration. The information can then be used for
 diagnostic purposes and debugging. Sos is commonly used to help
 support technicians and developers.
confinement: devmode

apps:
  sosreport:
    command: sosreport --config-file $SNAP/etc/sos.conf

parts:
  sos-src:
    source: https://github.com/sosreport/sosreport.git
    plugin: python
    python-version: "python2"
    prepare: make updateversion
    install: cp ./sos.conf $SNAPCRAFT_PART_INSTALL/etc/sos.conf
